label:  ["ei_ego_network_2"]
save_dir: ./logs/centrality/ba_betweeness_m-3_ninit-20_n-1000/
problem_name: centrality
n_exp: 10
plot:
  n_stop: 100
bo_settings:
  batch_size: 1
  max_iters: 100
  # the maximum hop distance to the centre node when constructing the local context graph
  max_radius: 10

  # the init size of the local context graph. If None, it can be as big as the entire graph.
  context_graph_nnode_init: 200
  
  tr_settings:    # settings related to the trust region on the graph search space
    n_nodes_min: 10         # the min number of nodes in the trust region
    trust_region_multiplier: 1.5 
    succ_tol: 10       # success tolerance
    fail_tol: 30      # fail tolerance
  
problem_settings:
  n: 1000
  random_graph_type: "ba" #"ws" # sbm, ba, ws
  feature_name: "betweenness" #"betweenness" eigenvector_centrality
  n_init: 20
  m: 3
    
